dir: "{{.InterfaceDirRelative }}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceNameSnake}}.go"
all: false
packages:
  task/repository:
    interfaces:
      ITaskRepository:
        config:
          # Specifically define filename since .InterfaceNameSnake would return i_submission_service.go
          filename: "task_repository.go"
  task/service:
    interfaces:
      ITaskService:
        config:
          # Specifically define filename since .InterfaceNameSnake would return i_submission_service.go
          filename: "task_service.go"