// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "task/persistence/models"

	mock "github.com/stretchr/testify/mock"
)

// ITaskRepository is an autogenerated mock type for the ITaskRepository type
type ITaskRepository struct {
	mock.Mock
}

type ITaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ITaskRepository) EXPECT() *ITaskRepository_Expecter {
	return &ITaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *ITaskRepository) Create(ctx context.Context, user *models.Task) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Task) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ITaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ITaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.Task
func (_e *ITaskRepository_Expecter) Create(ctx interface{}, user interface{}) *ITaskRepository_Create_Call {
	return &ITaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *ITaskRepository_Create_Call) Run(run func(ctx context.Context, user *models.Task)) *ITaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Task))
	})
	return _c
}

func (_c *ITaskRepository_Create_Call) Return(_a0 error) *ITaskRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITaskRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Task) error) *ITaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewITaskRepository creates a new instance of ITaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITaskRepository {
	mock := &ITaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
